# Generated by Django 2.1.5 on 2019-01-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='justificativa',
            field=models.CharField(default=True, max_length=400),
            preserve_default=False,
        ),
    ]
