# Generated by Django 2.1.5 on 2019-01-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem_postagem',
            field=models.ImageField(blank=True, null=True, upload_to='timeline_fotos'),
        ),
    ]
